AWSTemplateFormatVersion: 2010-09-09

Parameters:
  PlatformName:
    Type: String
  ProductName:
    Type: String
  ProjectName:
    Type: String
  AllowEcsPolicy:
    Type: CommaDelimitedList
  ContainerName:
    Type: String
  ContainerPort:
    Type: Number
  DesiredCount:
    Type: Number
  TaskCpu:
    Type: Number
  TaskMemory:
    Type: Number

Resources:
  IamRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/ecs/iam.yml
      Parameters:
        ProjectName: !Ref ProjectName
        AllowEcsPolicy: !Join [',', !Ref AllowEcsPolicy]

  Foundations:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/ecs/foundations.yml
      Parameters:
        ProjectName: !Ref ProjectName

  AppMesh:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/ecs/mesh.yml
      Parameters:
        ProjectName: !Ref ProjectName
        ContainerPort: !Ref ContainerPort
        MeshName: { 'Fn::ImportValue': !Sub "${ProductName}:ServiceMesh" }
        PrivateNamespace: { 'Fn::ImportValue': !Sub "${ProductName}:PrivateNamespace" }

  TaskDefinitions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./.task-definitions.yml
      Parameters:
        ProjectName: !Ref ProjectName
        ContainerName: !Ref ContainerName
        ContainerPort: !Ref ContainerPort
        EcsTaskExecutionRoleArn: !GetAtt [IamRoles, Outputs.EcsTaskExecutionRole]
        EcsTaskRoleArn: !GetAtt [IamRoles, Outputs.EcsTaskRoleArn]
        LogGroup: !GetAtt [Foundations, Outputs.LogGroup]
        RepositoryURI: !GetAtt [Foundations, Outputs.RepositoryURI]
        TaskCpu: !Ref TaskCpu
        TaskMemory: !Ref TaskMemory
        VirtualNodeName: !GetAtt [AppMesh, Outputs.VirtualNodeName]
        VirtualNodeArn: !GetAtt [AppMesh, Outputs.VirtualNodeArn]

  Service:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/ecs/services/internal.yml
      Parameters:
        ProjectName: !Ref ProjectName
        ClusterArn: { 'Fn::ImportValue': !Sub "${ProductName}:ClusterArn" }
        DesiredCount: !Ref DesiredCount
        NamespaceId: { 'Fn::ImportValue': !Sub "${ProductName}:ServiceDiscoveryId" }
        ProtectSubnets: !Join [',', [{ 'Fn::ImportValue': !Sub "${PlatformName}:ProtectSubnetA"}, { 'Fn::ImportValue': !Sub "${PlatformName}:ProtectSubnetC"}, { 'Fn::ImportValue': !Sub "${PlatformName}:ProtectSubnetD"}]]
        SecurityGroups: !Join [',', [{ 'Fn::ImportValue': !Sub "${PlatformName}:SecurityGroup" }, { 'Fn::ImportValue': !Sub "${ProductName}:SecurityGroup" }]]
        TaskDefinitionArn: !GetAtt [TaskDefinitions, Outputs.TaskDefinitionArn]
