
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  PlatformName:
    Type: String

Resources:
  EC2RoleforSSM:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
      RoleName: !Sub ${PlatformName}-ec2-role-for-ssm

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${PlatformName}-ec2-profile-for-ssm
      Roles:
        - !Ref EC2RoleforSSM

  ChatbotRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - chatbot.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
      RoleName: !Sub ${PlatformName}-chatbot-role

Outputs:
  ChatbotRoleArn:
    Value: !GetAtt ChatbotRole.Arn
    Export:
      Name: !Sub ${PlatformName}:ChatbotRoleArn
