AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String
  ContainerPort:
    Type: Number
  MeshName:
    Type: String
  PrivateNamespace:
    Type: String

Resources:
  VirtualService:
    Type: AWS::AppMesh::VirtualService
    Properties:
      MeshName: !Ref MeshName
      VirtualServiceName: !Sub ${ProjectName}.${PrivateNamespace}
      Spec:
        Provider:
          VirtualRouter:
            VirtualRouterName: !GetAtt VirtualRouter.VirtualRouterName

  VirtualRouter:
    Type: AWS::AppMesh::VirtualRouter
    Properties:
      MeshName: !Ref MeshName
      VirtualRouterName: !Ref ProjectName
      Spec:
        Listeners:
          - PortMapping:
              Port: !Ref ContainerPort
              Protocol: http

  Route:
    Type: AWS::AppMesh::Route
    Properties:
      MeshName: !Ref MeshName
      RouteName: !Ref ProjectName
      Spec:
        HttpRoute:
          Action:
            WeightedTargets:
              - VirtualNode: !GetAtt VirtualNode.VirtualNodeName
                Weight: 1
          Match:
            Prefix: /
      VirtualRouterName: !GetAtt VirtualRouter.VirtualRouterName

  VirtualNode:
    Type: AWS::AppMesh::VirtualNode
    Properties:
      MeshName: !Ref MeshName
      VirtualNodeName: !Ref ProjectName
      Spec:
        Listeners:
          - PortMapping:
              Port: !Ref ContainerPort
              Protocol: http
            HealthCheck:
              Protocol: http
              Path: /health
              HealthyThreshold: 2
              UnhealthyThreshold: 2
              TimeoutMillis: 2000
              IntervalMillis: 5000
        ServiceDiscovery:
          DNS:
            Hostname: !Sub ${ProjectName}.${PrivateNamespace}

Outputs:
  VirtualNodeArn:
    Value: !GetAtt VirtualNode.Arn
  VirtualNodeName:
    Value: !GetAtt VirtualNode.VirtualNodeName
  VirtualServiceName:
    Value: !GetAtt VirtualService.VirtualServiceName
