AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String
  IamRoleArn:
    Type: String
  SlackChannelId:
    Type: String
  SlackWorkspaceId:
    Type: String

Resources:
  SlackChannelConfiguration:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties:
      ConfigurationName: !Sub ${ProjectName}-chatbot
      IamRoleArn: !Ref IamRoleArn
      LoggingLevel: ERROR
      SlackChannelId: !Ref SlackChannelId
      SlackWorkspaceId: !Ref SlackWorkspaceId

Outputs:
  SlackChannelConfiguration:
    Value: !Ref SlackChannelConfiguration
