AWSTemplateFormatVersion: 2010-09-09

Parameters:
  PlatformName:
    Type: String
  ProductName:
    Type: String
  CallbackURLs:
    Type: String
  DomainName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  CognitoUserPool:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../cognito.yml
      Parameters:
        PlatformName: !Ref PlatformName
        CallbackURLs: !Ref CallbackURLs
        CertificateArn: { 'Fn::ImportValue': !Sub "${PlatformName}:CertificateArn" }
        DomainName: !Ref DomainName

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../vpc.yml
      Parameters:
        PlatformName: !Ref PlatformName
        ProductName: !Ref ProductName
        VpcId: !Ref VpcId
