AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String
  ArtifactBucket:
    Type: String
  BuildProject:
    Type: String
  CICredentialArn:
    Type: String
  ClusterName:
    Type: String
  CodePipelineRoleArn:
    Type: String
  GitHubBranch:
    Type: String
  GitHubOwner:
    Type: String
  GitHubRepository:
    Type: String
  ReleaseProject:
    Type: String
  SlackChannelConfiguration:
    Type: String
  TaggingProject:
    Type: String

Resources:
  CodePipelineNotificationRule:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      DetailType: FULL
      Resource: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CodePipeline}"
      EventTypeIds:
        # aws codestar-notifications list-event-types --filters Name=SERVICE_NAME,Value=CodePipeline | jq -r '.'
        - codepipeline-pipeline-pipeline-execution-superseded
        - codepipeline-pipeline-pipeline-execution-failed
      Targets:
        - TargetType: AWSChatbotSlack
          TargetAddress: !Ref SlackChannelConfiguration
      Name: !Ref ProjectName

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref ArtifactBucket
        Type: S3
      Name: !Ref ProjectName
      RestartExecutionOnUpdate: false
      RoleArn: !Ref CodePipelineRoleArn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceCode
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepository
                Branch: !Ref GitHubBranch
                OAuthToken: !Sub '{{resolve:secretsmanager:${CICredentialArn}:SecretString:GitHubAccessToken}}'
              OutputArtifacts:
                - Name: SourceCode
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref BuildProject
              OutputArtifacts:
                - Name: BuildImage
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              InputArtifacts:
                - Name: BuildImage
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ECS
                Version: 1
              Configuration:
                ClusterName: !Ref ClusterName
                FileName: imagedefinitions.json
                ServiceName: !Ref ProjectName
              OutputArtifacts: []
              RunOrder: 1
        - Name: Approval
          Actions:
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: 1
                Provider: Manual
              RunOrder: 1
        - Name: Release
          Actions:
            - Name: GitHub
              InputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref TaggingProject
              RunOrder: 1
            - Name: Release
              InputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref ReleaseProject
              RunOrder: 2
