AWSTemplateFormatVersion: '2010-09-09'
Description: ''

Parameters:
  ProductName:
    Type: String

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [!Ref 'AWS::AccountId', arfifact, bucket]]
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  ArtifactBucket:
    Value: !Ref ArtifactBucket
    Export:
      Name: !Join [':', [!Ref ProductName, ArtifactBucket]]
