AWSTemplateFormatVersion: 2010-09-09

Parameters:
  PlatformName:
    Type: String
  ProductName:
    Type: String
  CallbackURLs:
    Type: String
  DomainName:
    Type: String
  PrivateNamespace:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  CognitoUserPool:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cognito.yml
      Parameters:
        PlatformName: !Ref PlatformName
        CallbackURLs: !Ref CallbackURLs
        CertificateArn: { 'Fn::ImportValue': !Sub "${PlatformName}:CertificateArn" }
        DomainName: !Ref DomainName

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../modules/base/vpc.yml
      Parameters:
        PlatformName: !Ref PlatformName
        ProductName: !Ref ProductName
        VpcId: !Ref VpcId

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../modules/base/ecs.yml
      Parameters:
        PlatformName: !Ref PlatformName
        ProductName: !Ref ProductName
        PrivateNamespace: !Ref PrivateNamespace
        VpcId: !Ref VpcId
