ContainerDefinitions:
  Environment:
    - Name: RAILS_LOG_TO_STDOUT
      Value: true
    - Name: AWS_ECS_CLUSTER_NAME
      Value: platform
    - Name: AWS_ECS_SERVICE_NAME
      Value: iam
    - Name: AWS_COGNITO_USERPOOL_ID
      Value: "!ImportValue platform:UserPool"
