AWSTemplateFormatVersion: 2010-09-09

Parameters:
  PlatformName:
    Type: String
  ProductName:
    Type: String
  CallbackURLs:
    Type: String
  DomainName:
    Type: String
  PrivateNamespace:
    Type: String

Resources:
  Cognito:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cognito.yml
      Parameters:
        ProductName: !Ref ProductName
        CallbackURLs: !Ref CallbackURLs
        CertificateArn: { 'Fn::ImportValue': !Sub "${PlatformName}:CertificateArn" }
        DomainName: !Ref DomainName

  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yml
      Parameters:
        ProductName: !Ref ProductName
        VpcId: { 'Fn::ImportValue': !Sub "${PlatformName}:VpcId" }

  Ecs:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../modules/ecs.yml
      Parameters:
        ProductName: !Ref ProductName
        PrivateNamespace: !Ref PrivateNamespace
        VpcId: { 'Fn::ImportValue': !Sub "${PlatformName}:VpcId" }

  AuroraServerless:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./rds.yml
      Parameters:
        ProductName: !Ref ProductName
        MasterUsername: !Ref PlatformName
        PrivateSubnets: !Join [',', [{ 'Fn::ImportValue': !Sub "${PlatformName}:PrivateSubnetA"}, { 'Fn::ImportValue': !Sub "${PlatformName}:PrivateSubnetC"}, { 'Fn::ImportValue': !Sub "${PlatformName}:PrivateSubnetD"}]]
        SecurityGroups: !Join [',', [!GetAtt [Vpc, Outputs.SecurityGroup]]]
