AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProductName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ProductName}-sg
      GroupName: !Sub ${ProductName}-sg
      GroupDescription: !Sub Allows traffic between ${ProductName} resources.
      VpcId: !Ref VpcId

  SecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref SecurityGroup

Outputs:
  SecurityGroup:
    Value: !Ref SecurityGroup
    Export:
      Name: !Sub ${ProductName}:SecurityGroup
