AWSTemplateFormatVersion: 2010-09-09

Parameters:
  PlatformName:
    Type: String
  ProductName:
    Type: String
  ProjectName:
    Type: String
  BuildDirectory:
    Type: String
  CICredentialArn:
    Type: String
  ContainerName:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prd
  GitHubBranch:
    Type: String
  GitHubOwner:
    Type: String
  GitHubRepository:
    Type: String
  PrincipalID:
    Type: String
  ReleaseID:
    Type: String
  ReleaseVersion:
    Type: String
  SlackChannelId:
    Type: String
  SlackWorkspaceId:
    Type: String

Conditions:
  IsDevelopment:
    !Equals [!Ref Environment, dev]
  IsProduction:
    !Equals [!Ref Environment, prd]

Resources:
  IamRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../modules/pipeline/iam.yml
      Parameters:
        ProjectName: !Ref ProjectName

  Foundations:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../modules/pipeline/foundations.yml
      Parameters:
        ProjectName: !Ref ProjectName
        IamRoleArn: { 'Fn::ImportValue': !Sub "${PlatformName}:ChatbotRoleArn" }
        SlackChannelId: !Ref SlackChannelId
        SlackWorkspaceId: !Ref SlackWorkspaceId

  # --------------------------------------------------
  # Development
  # --------------------------------------------------
  CodeBuild:
    Type: AWS::CloudFormation::Stack
    Condition: IsDevelopment
    Properties:
      TemplateURL: ../../modules/pipeline/dev/codebuild.yml
      Parameters:
        ProjectName: !Ref ProjectName
        BuildDirectory: !Ref BuildDirectory
        CICredentialArn: !Ref CICredentialArn
        CodeBuildRole: !GetAtt [IamRoles, Outputs.CodeBuildRole]
        ContainerName: !Ref ContainerName
        GitHubBranch: !Ref GitHubBranch
        GitHubOwner: !Ref GitHubOwner
        GitHubRepository: !Ref GitHubRepository
        ProtectSubnets: !Join [',', [{ 'Fn::ImportValue': !Sub "${PlatformName}:ProtectSubnetA"}, { 'Fn::ImportValue': !Sub "${PlatformName}:ProtectSubnetC"}, { 'Fn::ImportValue': !Sub "${PlatformName}:ProtectSubnetD"}]]
        ReleaseID: !Ref ReleaseID
        ReleaseVersion: !Ref ReleaseVersion
        SecurityGroups: !Join [',', [{ 'Fn::ImportValue': !Sub "${ProductName}:SecurityGroup" }]]
        VpcId: { 'Fn::ImportValue': !Sub "${PlatformName}:VpcId" }

  CodePipeline:
    Type: AWS::CloudFormation::Stack
    Condition: IsDevelopment
    Properties:
      TemplateURL: ../../modules/pipeline/dev/codepipeline.yml
      Parameters:
        ProjectName: !Ref ProjectName
        ArtifactBucket: { 'Fn::ImportValue': !Sub "${PlatformName}:ArtifactBucket" }
        BuildProject: !GetAtt [CodeBuild, Outputs.DockerBuild]
        CICredentialArn: !Ref CICredentialArn
        ClusterName: { 'Fn::ImportValue': !Sub "${ProductName}:ClusterName" }
        CodePipelineRoleArn: !GetAtt [IamRoles, Outputs.CodePipelineRoleArn]
        GitHubBranch: !Ref GitHubBranch
        GitHubOwner: !Ref GitHubOwner
        GitHubRepository: !Ref GitHubRepository
        ReleaseProject: !GetAtt [CodeBuild, Outputs.Release]
        SlackChannelConfiguration: !GetAtt [Foundations, Outputs.SlackChannelConfiguration]
        TaggingProject: !GetAtt [CodeBuild, Outputs.GitHubTag]

  # --------------------------------------------------
  # Production
  # --------------------------------------------------
  CodeBuild:
    Type: AWS::CloudFormation::Stack
    Condition: IsProduction
    Properties:
      TemplateURL: ../../modules/pipeline/prd/codebuild.yml
      Parameters:
        ProjectName: !Ref ProjectName
        CICredentialArn: !Ref CICredentialArn
        CodeBuildRole: !GetAtt [IamRoles, Outputs.CodeBuildRole]
        ContainerName: !Ref ContainerName
        GitHubOwner: !Ref GitHubOwner
        GitHubRepository: !Ref GitHubRepository
        ProtectSubnets: !Join [',', [{ 'Fn::ImportValue': !Sub "${PlatformName}:ProtectSubnetA"}, { 'Fn::ImportValue': !Sub "${PlatformName}:ProtectSubnetC"}, { 'Fn::ImportValue': !Sub "${PlatformName}:ProtectSubnetD"}]]
        ReleaseVersion: !Ref ReleaseVersion
        SecurityGroups: !Join [',', [{ 'Fn::ImportValue': !Sub "${ProductName}:SecurityGroup" }]]
        VpcId: { 'Fn::ImportValue': !Sub "${PlatformName}:VpcId" }

  CodePipeline:
    Type: AWS::CloudFormation::Stack
    Condition: IsProduction
    Properties:
      TemplateURL: ../../modules/pipeline/prd/codepipeline.yml
      Parameters:
        ProjectName: !Ref ProjectName
        ArtifactBucket: { 'Fn::ImportValue': !Sub "${PlatformName}:ArtifactBucket" }
        BuildProject: !GetAtt [CodeBuild, Outputs.DockerBuild]
        CodePipelineRoleArn: !GetAtt [IamRoles, Outputs.CodePipelineRoleArn]
        ClusterName: { 'Fn::ImportValue': !Sub "${ProductName}:ClusterName" }
        EcrRepository: !Ref ProjectName
        ReleaseVersion: !Ref ReleaseVersion
        SlackChannelConfiguration: !GetAtt [Foundations, Outputs.SlackChannelConfiguration]

  CodePipelineEvent:
    Type: AWS::CloudFormation::Stack
    Condition: IsProduction
    Properties:
      TemplateURL: ../../modules/pipeline/prd/event.yml
      Parameters:
        ProjectName: !Ref ProjectName
        CodePipeline: !Ref ProjectName
        EcrRepository: !GetAtt [CodePipeline, Outputs.CodePipeline]
        PrincipalID: !Ref PrincipalID
        ReleaseVersion: !Ref ReleaseVersion
