AWSTemplateFormatVersion: 2010-09-09

Parameters:
  PlatformName:
    Type: String
  ProductName:
    Type: String
  ProjectName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  DomainName:
    Type: String
  HostedZoneId:
    Type: String
  CallbackURLs:
    Type: String

Resources:
  # Route53:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: ./route53.yml
  #     Parameters:
  #       PlatformName: !Ref PlatformName
  #       ProductName: !Ref ProductName
  #       ProjectName: !Ref ProjectName
  #       DomainName: !Ref DomainName
  #       HostedZoneId: !Ref HostedZoneId

  # CognitoUserPool:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: ./cognito.yml
  #     Parameters:
  #       PlatformName: !Ref PlatformName
  #       ProductName: !Ref ProductName
  #       ProjectName: !Ref ProjectName
  #       CallbackURLs: !Ref CallbackURLs
  #       DomainName: !Ref DomainName
  #       CertificateArn: !GetAtt [Route53, Outputs.CertificateArn]

  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./iam.yml
      Parameters:
        PlatformName: !Ref PlatformName
        ProductName: !Ref ProductName
        ProjectName: !Ref ProjectName

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yml
      Parameters:
        PlatformName: !Ref PlatformName
        ProductName: !Ref ProductName
        ProjectName: !Ref ProjectName
        VpcId: !Ref VpcId

  # ElasticLoadBalancer:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: ./elb.yml
  #     Parameters:
  #       PlatformName: !Ref PlatformName
  #       ProductName: !Ref ProductName
  #       ProjectName: !Ref ProjectName
  #       HostedZoneId: !Ref HostedZoneId
  #       DomainName: !Ref DomainName
  #       PublicSubnets: !Join [',', !Ref PublicSubnets]
  #       CertificateArn: !GetAtt [Route53, Outputs.CertificateArn]
  #       SecurityGroups: !Join [',', [!GetAtt [VPC, Outputs.SecurityGroup], !GetAtt [VPC, Outputs.AllowGlobalTrafficSg]]]
