AWSTemplateFormatVersion: 2010-09-09

Parameters:
  PlatformName:
    Type: String
  ProductName:
    Type: String
  ProjectName:
    Type: String
  DesiredCount:
    Type: Number
  TaskDefinitionArn:
    Type: String
  ProtectedSubnets:
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  ServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      HealthCheckCustomConfig:
        FailureThreshold: 1
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 60
        NamespaceId: { 'Fn::ImportValue': !Sub "${ProductName}:ServiceDiscoveryId" }
      Name: !Ref ProjectName

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: { 'Fn::ImportValue': !Sub "${ProductName}:ClusterArn" }
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED   # TODO: Set to DISABLED when using NAT Gateway
          SecurityGroups:
            - { 'Fn::ImportValue': !Sub "${PlatformName}:SecurityGroup" }
          Subnets: !Ref ProtectedSubnets
      ServiceName: !Ref ProjectName
      ServiceRegistries:
        - RegistryArn: !GetAtt ServiceDiscovery.Arn
      TaskDefinition: !Ref TaskDefinitionArn
