AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProductName:
    Type: String
  PrivateNamespace:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ProductName

  ServiceMesh:
    Type: AWS::AppMesh::Mesh
    Properties:
      MeshName: !Ref ProductName
      Spec:
        EgressFilter:
          Type: DROP_ALL

  ServiceDiscovery:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Vpc: !Ref VpcId
      Name: !Ref PrivateNamespace

Outputs:
  ClusterName:
    Value: !Ref Cluster
    Export:
      Name: !Sub ${ProductName}:ClusterName

  ClusterArn:
    Value: !GetAtt Cluster.Arn
    Export:
      Name: !Sub ${ProductName}:ClusterArn

  ServiceMesh:
    Value: !GetAtt ServiceMesh.MeshName
    Export:
      Name: !Sub ${ProductName}:ServiceMesh

  ServiceDiscoveryId:
    Value: !GetAtt ServiceDiscovery.Id
    Export:
      Name: !Sub ${ProductName}:ServiceDiscoveryId

  PrivateNamespace:
    Value: !Ref PrivateNamespace
    Export:
      Name: !Sub ${ProductName}:PrivateNamespace
