AWSTemplateFormatVersion: 2010-09-09

Parameters:
  PlatformName:
    Type: String
  ProductName:
    Type: String
  ProjectName:
    Type: String
  ProtectedSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  AllowEcsPolicy:
    Type: CommaDelimitedList
  ContainerName:
    Type: String
  ContainerPort:
    Type: Number
  TaskCpu:
    Type: Number
  TaskMemory:
    Type: Number
  DesiredCount:
    Type: Number

Resources:
  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../../modules/ecs/iam.yml
      Parameters:
        PlatformName: !Ref PlatformName
        ProductName: !Ref ProductName
        ProjectName: !Ref ProjectName
        AllowEcsPolicy: !Join [',', !Ref AllowEcsPolicy]

  Foundations:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../../modules/ecs/foundations.yml
      Parameters:
        PlatformName: !Ref PlatformName
        ProductName: !Ref ProductName
        ProjectName: !Ref ProjectName

  AppMesh:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../../modules/ecs/mesh/internal.yml
      Parameters:
        PlatformName: !Ref PlatformName
        ProductName: !Ref ProductName
        ProjectName: !Ref ProjectName
        ContainerPort: !Ref ContainerPort

  TaskDefinitions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../../modules/ecs/tasks/internal.yml
      Parameters:
        PlatformName: !Ref PlatformName
        ProductName: !Ref ProductName
        ProjectName: !Ref ProjectName
        ContainerName: !Ref ContainerName
        ContainerPort: !Ref ContainerPort
        TaskCpu: !Ref TaskCpu
        TaskMemory: !Ref TaskMemory
        EcsTaskExecutionRoleArn: !GetAtt [IAM, Outputs.EcsTaskExecutionRole]
        EcsTaskRoleArn: !GetAtt [IAM, Outputs.EcsTaskRoleArn]
        RepositoryURI: !GetAtt [Foundations, Outputs.RepositoryURI]
        LogGroup: !GetAtt [Foundations, Outputs.LogGroup]
        VirtualNodeName: !GetAtt [AppMesh, Outputs.VirtualNodeName]
        VirtualNodeArn: !GetAtt [AppMesh, Outputs.VirtualNodeArn]

  Service:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../../modules/ecs/services/internal.yml
      Parameters:
        PlatformName: !Ref PlatformName
        ProductName: !Ref ProductName
        ProjectName: !Ref ProjectName
        DesiredCount: !Ref DesiredCount
        TaskDefinitionArn: !GetAtt [TaskDefinitions, Outputs.TaskDefinitionArn]
        ProtectedSubnets: !Join [',', !Ref ProtectedSubnets]
