AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String
  ArtifactBucket:
    Type: String
  BuildProject:
    Type: String
  CodePipelineRoleArn:
    Type: String
  ClusterName:
    Type: String
  EcrRepository:
    Type: String
  ReleaseVersion:
    Type: String
  SlackChannelConfiguration:
    Type: String

Resources:
  CodePipelineNotificationRule:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      DetailType: FULL
      Resource: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CodePipeline}"
      EventTypeIds:
        # aws codestar-notifications list-event-types --filters Name=SERVICE_NAME,Value=CodePipeline | jq -r '.'
        - codepipeline-pipeline-pipeline-execution-succeeded
        - codepipeline-pipeline-pipeline-execution-failed
      Targets:
        - TargetType: AWSChatbotSlack
          TargetAddress: !Ref SlackChannelConfiguration
      Name: !Ref ProjectName

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref ArtifactBucket
        Type: S3
      Name: !Ref ProjectName
      RestartExecutionOnUpdate: false
      RoleArn: !Ref CodePipelineRoleArn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceImage
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: ECR
                Version: 1
              Configuration:
                ImageTag: !Ref ReleaseVersion
                RepositoryName: !Ref EcrRepository
              OutputArtifacts:
                - Name: SourceImage
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: SourceImage
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref BuildProject
              OutputArtifacts:
                - Name: BuildImage
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              InputArtifacts:
                - Name: BuildImage
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ECS
                Version: 1
              Configuration:
                ClusterName: !Ref ClusterName
                FileName: imagedefinitions.json
                ServiceName: !Ref ProjectName
              OutputArtifacts: []
              RunOrder: 1

Outputs:
  CodePipeline:
    Value: !Ref CodePipeline
