AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String
  CodePipeline:
    Type: String
  EcrRepository:
    Type: String
  PrincipalID:
    Type: String
  ReleaseVersion:
    Type: String

Resources:
  ReleaseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${PrincipalID}:root"
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
      RoleName: !Sub ${ProjectName}-release-role

  CodePipelineEventRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub codepipeline-event
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CodePipeline}"
      RoleName: !Sub ${ProjectName}-codepipeline-event-role

  CodePipelineEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.ecr
        detail:
          eventName:
            - PutImage
          requestParameters:
            repositoryName:
              - !Ref EcrRepository
            imageTag:
              - !Ref ReleaseVersion
      Targets:
        - Arn: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CodePipeline}"
          RoleArn: !GetAtt CodePipelineEventRole.Arn
          Id: !Ref ProjectName
      Name: !Ref ProjectName
