AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProductName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ProductName

  Mesh:
    Type: AWS::AppMesh::Mesh
    Properties:
      MeshName: !Ref ProductName

Outputs:
  ClusterArn:
    Value: !GetAtt Cluster.Arn
    Export:
      Name: !Sub ${ProductName}:ClusterArn
