AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProductName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateDnsNamespace:
    Type: String

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ProductName

  Mesh:
    Type: AWS::AppMesh::Mesh
    Properties:
      MeshName: !Ref ProductName

  PrivateDnsNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Vpc: !Ref VpcId
      Name: !Ref PrivateDnsNamespace

Outputs:
  ClusterArn:
    Value: !GetAtt Cluster.Arn
    Export:
      Name: !Sub ${ProductName}:ClusterArn

  Mesh:
    Value: !Ref Mesh
    Export:
      Name: !Sub ${ProductName}:Mesh
