AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProductName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  ServicesDomain:
    Type: String

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ProductName

  ServiceMesh:
    Type: AWS::AppMesh::Mesh
    Properties:
      MeshName: !Ref ProductName

  ServiceDiscovery:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Vpc: !Ref VpcId
      Name: !Ref ServicesDomain

Outputs:
  ClusterArn:
    Value: !GetAtt Cluster.Arn
    Export:
      Name: !Sub ${ProductName}:ClusterArn

  ServiceMesh:
    Value: !GetAtt ServiceMesh.MeshName
    Export:
      Name: !Sub ${ProductName}:ServiceMesh
