AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String
  MeshName:
    Type: String
  VirtualServiceName:
    Type: String

Resources:
  VirtualGateway:
    Type: AWS::AppMesh::VirtualGateway
    Properties:
      MeshName: !Ref MeshName
      Spec:
        Listeners:
          - PortMapping:
              Port: 9080
              Protocol: http
      VirtualGatewayName: !Ref ProjectName

  GatewayRoute:
    Type: AWS::AppMesh::GatewayRoute
    Properties:
      GatewayRouteName: !Ref ProjectName
      MeshName: !Ref MeshName
      Spec:
        HttpRoute:
          Action:
            Target:
              VirtualService:
                VirtualServiceName: !Ref VirtualServiceName
          Match:
            Prefix: /
      VirtualGatewayName: !GetAtt VirtualGateway.VirtualGatewayName
