
AWSTemplateFormatVersion: 2010-09-09
Description: ''

Parameters:
  ProductName:
    Type: String

Resources:
  EC2RoleforSSM:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
      RoleName: !Sub ${ProductName}-ec2-role-for-ssm

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${ProductName}-ec2-profile-for-ssm
      Roles:
        - !Ref EC2RoleforSSM

  ChatbotRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - chatbot.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
      RoleName: !Sub ${ProductName}-chatbot-role

Outputs:
  ChatbotRole:
    Value: !GetAtt ChatbotRole.Arn
    Export:
          Name: !Join [':', [!Ref ProductName, ChatbotRoleArn]]
