AWSTemplateFormatVersion: 2010-09-09

Resources:
  Panicboat:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    Properties:
      Name: panicboat.net

  RecordSetPlatform:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !GetAtt Panicboat.Id
      Comment: DNS name for platform
      Name: _b00ae4d79e81e66d79761b647ecd900e.panicboat.net.
      Type: CNAME
      ResourceRecords:
        - _d97864ced00ecea9160d0a8d8c220eef.jddtvkljgg.acm-validations.aws.
      TTL: 600
